/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BancoRouteImport } from './routes/banco'
import { Route as ErrosRouteImport } from './routes/erros'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as ExamSandboxRouteImport } from './routes/exam-sandbox'
import { Route as HistoricoRouteImport } from './routes/historico'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BancoRoute = BancoRouteImport.update({
  id: '/banco',
  path: '/banco',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrosRoute = ErrosRouteImport.update({
  id: '/erros',
  path: '/erros',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamSandboxRoute = ExamSandboxRouteImport.update({
  id: '/exam-sandbox',
  path: '/exam-sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banco': typeof BancoRoute
  '/erros': typeof ErrosRoute
  '/exam': typeof ExamRoute
  '/exam-sandbox': typeof ExamSandboxRoute
  '/historico': typeof HistoricoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banco': typeof BancoRoute
  '/erros': typeof ErrosRoute
  '/exam': typeof ExamRoute
  '/exam-sandbox': typeof ExamSandboxRoute
  '/historico': typeof HistoricoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banco': typeof BancoRoute
  '/erros': typeof ErrosRoute
  '/exam': typeof ExamRoute
  '/exam-sandbox': typeof ExamSandboxRoute
  '/historico': typeof HistoricoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/banco' | '/erros' | '/exam' | '/exam-sandbox' | '/historico'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/banco' | '/erros' | '/exam' | '/exam-sandbox' | '/historico'
  id:
    | '__root__'
    | '/'
    | '/banco'
    | '/erros'
    | '/exam'
    | '/exam-sandbox'
    | '/historico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BancoRoute: typeof BancoRoute
  ErrosRoute: typeof ErrosRoute
  ExamRoute: typeof ExamRoute
  ExamSandboxRoute: typeof ExamSandboxRoute
  HistoricoRoute: typeof HistoricoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banco': {
      id: '/banco'
      path: '/banco'
      fullPath: '/banco'
      preLoaderRoute: typeof BancoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erros': {
      id: '/erros'
      path: '/erros'
      fullPath: '/erros'
      preLoaderRoute: typeof ErrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-sandbox': {
      id: '/exam-sandbox'
      path: '/exam-sandbox'
      fullPath: '/exam-sandbox'
      preLoaderRoute: typeof ExamSandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BancoRoute: BancoRoute,
  ErrosRoute: ErrosRoute,
  ExamRoute: ExamRoute,
  ExamSandboxRoute: ExamSandboxRoute,
  HistoricoRoute: HistoricoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
